import type { Metadata } from "next";
import '@/styles/globals.css';
import { jost } from '@/lib/ui/fonts';
import NavLinks from '@/components/nav-links'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ThemeProvider } from "@/components/theme-context";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jost.className} antialiased pt-10`}
      >
         <ThemeProvider>
          <NavLinks/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
